apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app-container
        image: matheusgomes1/tc-hackaton:1.3
        resources:
          limits:
            memory: 100Mi
            ephemeral-storage: "2Gi"
        env:
        - name: AWS_ACCESS_KEY_ID
          value: ""
        - name: AWS_SECRET_ACCESS_KEY
          value: ""
        - name: AWS_REGION
          value: "us-east-1"
        - name: AWS_SESSION_TOKEN
          value: ""
